apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
# secretGenerator:
# - name: traefik-certs
#   type: 'kubernetes.io/tls'
#   files:
#   - tls.key=config/certs/_wildcard.k8s.internal-key.pem
#   - tls.crt=config/certs/_wildcard.k8s.internal.pem
resources:
- manifests/traefik-secret.yaml
# - manifests/traefik-ingress-route.yaml
# - manifests/traefik-redirect-https.yaml
# - manifests/traefik-middlewares.yaml
# - manifests/traefik-tlsoption.yaml
# - manifests/traefik-tlsstore.yaml

