---
apiVersion: k3d.io/v1alpha2
kind: Simple
name: devops
servers: 1
agents: 1
ports:
  - port: 80:80 # same as `--port '80:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 443:443 # same as `--port '443:443@loadbalancer'`
    nodeFilters:
      - loadbalancer
registries: # define how registries should be created or used
  create: false # creates a default registry to be used with the cluster; same as `--registry-create`
  config: registry-config.yaml
volumes:
  - volume: ${K3S_MANIFESTS_DIR}:/var/lib/rancher/k3s/server/manifests
    nodeFilters:
      - server[0]
