# Redirect to https
http:
  middlewares:
    secured:
      chain:
        middlewares:
          - https-only

    https-only:
      redirectScheme:
        scheme: https

tls:
  certificates:
    - certFile: /certs/tls.crt
      keyFile: /certs/tls.key

  options:
    default:
      minVersion: VersionTLS12
      preferServerCipherSuites: true
