apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - '--providers.file.directory=/etc/traefik/dynamic_conf'
      - '--entrypoints.websecure.http.tls=true'
    volumes:
      - name: traefik-secret
        mountPath: '/certs'
        type: secret
      - name: traefik-config
        mountPath: '/etc/traefik/dynamic_conf'
        type: configMap
