apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-20.3.1+up20.3.0.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - '--entrypoints.websecure.http.tls=true'
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    volumes:
      - name: traefik-secret
        mountPath: '/certs'
        type: secret