spec:
  template:
    spec:
      volumes:
        - name: certs
          secret:
            secretName: traefik-certs
        - name: conf
          configMap:
            name: traefik-config
      containers:
        - name: traefik
          args:
            - '--global.checknewversion'
            - '--global.sendanonymoususage'
            - '--entryPoints.traefik.address=:9000/tcp'
            - '--entryPoints.web.address=:8000/tcp'
            - '--entryPoints.websecure.address=:8443/tcp'
            - '--api.dashboard=true'
            - '--ping=true'
            - '--providers.kubernetescrd'
            - '--providers.kubernetesingress'
            - >-
              --providers.kubernetesingress.ingressendpoint.publishedservice=kube-system/traefik
            - '--entrypoints.websecure.http.tls=true'
            - '--providers.file.directory=/etc/traefik/dynamic_conf'
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
            - name: conf
              readOnly: true
              mountPath: /etc/traefik/dynamic_conf
