apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: drone
spec:
  repo: https://charts.drone.io
  chart: drone
  valuesContent: |-
    extraVolumes:
      - name: traefik-certs
        secret:
          secretName: traefik-secret
    extraVolumeMounts:
      - name: traefik-certs
        mountPath: /opt/ssl/traefik
        readOnly: true
    extraSecretNamesForEnvFrom:
      - gitea-oauth-secrets
    env:
      DRONE_RPC_HOST: "drone.k8s.internal"
      DRONE_SERVER_PROTO: https
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_GITEA_SERVER: "https://git.k8s.internal"
      DRONE_GITEA_SKIP_VERIFY: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: drone
  namespace: default
  labels:
    app: drone
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`drone.k8s.internal`)
      services:
        - name: drone
          port: 80
