# Redirect to https
http:
  middlewares:
    secured:
      chain:
        middlewares:
          - https-only
          - forwareder-headers

    https-only:
      redirectScheme:
        scheme: https

    forwareder-headers:
      headers:
        hostsProxyHeaders: ["X-Forwarded-For", "X-Forwarded-Host"]

    xss-headers:
      headers:
        contentTypeNosniff: true
        browserXssFilter: true
        contentSecurityPolicy: "default-src 'self'; script-src 'self'"

tls:
  certificates:
    - certFile: /certs/tls.crt
      keyFile: /certs/tls.key

  options:
    default:
      minVersion: VersionTLS12
      preferServerCipherSuites: true