resources:
  limits:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

postgresql:
  persistence:
    size: 1Gi

gitea:
  admin:
    username: gitea_adm
    password: giteaP@ssw0rd
