additionalArguments:
  - '--providers.file.directory=/etc/traefik/dynamic_conf'
  - '--entrypoints.websecure.http.tls=true'
volumes:
  - name: traefik-certs
    mountPath: '/certs'
    type: secret
  - name: traefik-config
    mountPath: '/etc/traefik/dynamic_conf'
    type: configMap
