apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
spec:
  chart: traefik/traefik
  targetNamespace: kube-system
  valuesContent: |-
    additionalArguments:
      - '--providers.file.directory=/etc/traefik/dynamic_conf'
      - '--entrypoints.websecure.http.tls=true'
    volumes:
      - name: $(TRAEFIK_SECRET_NAME)
        mountPath: '/certs'
        type: secret
      - name: $(TRAEFIK_CONFIG_NAME)
        mountPath: '/etc/traefik/dynamic_conf'
        type: configMap
